site_name: TOPL Documentation
site_description: TOML extended with placeholders - comprehensive documentation
site_author: Adam Twardoch
site_url: https://terragonlabs.github.io/topl

repo_name: terragonlabs/topl
repo_url: https://github.com/terragonlabs/topl
edit_uri: edit/main/src_docs/md/

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true

nav:
  - Home:
    - md/index.md
  - Getting Started:
    - md/01-getting-started.md
  - Installation & Setup:
    - md/02-installation-setup.md
  - Basic Usage:
    - md/03-basic-usage.md
  - Two-Phase Resolution:
    - md/04-two-phase-resolution.md
  - CLI Reference:
    - md/05-cli-reference.md
  - API Reference:
    - md/06-api-reference.md
  - Configuration & Examples:
    - md/07-configuration-examples.md
  - Troubleshooting:
    - md/08-troubleshooting.md
  - Development & Contributing:
    - md/09-development-contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terragonlabs/topl
  version:
    provider: mike

copyright: Copyright &copy; 2024 Adam Twardoch, Terragon Labs