name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write  # For PyPI trusted publishing

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for version detection

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Build package
      run: uv build

    - name: Check build
      run: |
        ls -la dist/
        uv run twine check dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test-pypi:
    name: Test PyPI Release
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/topl/
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  pypi:
    name: PyPI Release
    needs: test-pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/topl/
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Generate Changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^ 2>/dev/null || echo "")
        if [ -z "$PREV_TAG" ]; then
          echo "No previous tag found, using all commits"
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse)
        else
          echo "Previous tag: $PREV_TAG"
          COMMITS=$(git log --pretty=format:"- %s (%h)" --reverse $PREV_TAG..${{ github.ref }})
        fi
        
        # Create changelog content
        echo "## What's Changed" > changelog.md
        echo "" >> changelog.md
        echo "$COMMITS" >> changelog.md
        echo "" >> changelog.md
        echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREV_TAG...${{ github.ref_name }}" >> changelog.md

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changelog.md
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: false